version: '2'
services:
 rviz:
    # build: .
    image: ros-rviz
    container_name: rviz
    hostname: rviz
    devices:
      - /dev/net/tun
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN       
    volumes:
      - "/tmp/.X11-unix:/tmp/.X11-unix"
      - /home/ubuntu/docker-volumes/rviz/zerotier-one:/var/lib/zerotier-one 
    environment:
      - "DISPLAY=:0"
      - "ZT_NETWORK=565799d8f6f7f87f"
      - "QT_X11_NO_MITSHM=1"
      - "ROS_MASTER_URI=http://master:11311"
#      - "ROS_MASTER_URI=http://ev3:11311"
    command: rosrun rviz rviz

