version: '2'
services:
  master:
    extends:
      file: "../ros-indigo-zt/docker-compose.yml"
      service: master
    extra_hosts:
      - "ev3dev:192.168.0.12"

  lsdslam:
    networks:
      rosnet:
        ipv4_address: 192.168.0.102
    extends:
      file: "../ros-indigo-zt/docker-compose.yml"
      service: master
    image: ros-lsdslam
    container_name: lsdslam
    hostname: lsdslam
    volumes:
      - /home/ubuntu/docker-volumes/node1/zerotier-one:/var/lib/zerotier-one 
    devices:
      - /dev/video1
    working_dir: /home/ros
    command: bash -i -c "sudo chmod 777 /dev/video1 && roslaunch launch/usbcam.launch & rosrun lsd_slam_viewer viewer & rosrun lsd_slam_core live_slam /image:=/usb_cam/image_raw _calib:=FOV_examle_calib.cfg"
#    command: bash


# TODO can we use extend for networks to avoid duplication ?
networks:
  rosnet:
    driver: macvlan
    driver_opts:
      parent: enp0s25
    ipam:
      config:
        - subnet: 192.168.0.0/24
          gateway: 192.168.0.1
