version: '2'
services:
  master:
    # build: .
  # image: toddsampson/ros-indigo-image_pipeline
    image: ros-indigo-zt
    container_name: master
    # TODO change in host's /etc/resolv.conf and remove this property 
    dns: 8.8.8.8
    networks:
      rosnet:
        ipv4_address: 192.168.0.100
#    dns: 52.51.247.240 
#    hostname: master
  #name: image_view
  #volumes_from:
  #- "rosmaster"
    devices:
      - /dev/net/tun
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN       
    volumes:
      - "/tmp/.X11-unix:/tmp/.X11-unix"
      - /home/ubuntu/docker-volumes/master/zerotier-one:/var/lib/zerotier-one 
    environment:
      - "DISPLAY=:1001"
      - "ZT_NETWORK=565799d8f6f7f87f"
# #    - "ROS_HOSTNAME=image_view"
      - "ROS_MASTER_URI=http://master:11311"
  #command: rosrun image_view image_view image:=/camera/compressed
# #  command: sudo zerotier-cli join 565799d8f6f7f87f    
  #  command: bash -c "sudo service zerotier-one start && sudo zerotier-cli join 565799d8f6f7f87f && bash"
    command: roscore -v
#  command: bash
  #command: roscore
  #command: rostopic list

networks:
  rosnet:
    driver: macvlan
    driver_opts:
      parent: wlp4s0  
    ipam:
      config:
        - subnet: 192.168.0.0/24
          gateway: 192.168.0.1  
