version: '2'
services:
  master:
    extends:
      file: "../ros-indigo-zt/docker-compose.yml"
      service: master
    hostname: masterleakimav
    dns_search: hopto.org

  teleop:
    extends:
      file: "../ros-indigo-zt/docker-compose.yml"
      service: master
    container_name: teleop
    hostname: node1leakimav
    dns_search: hopto.org
    volumes:
      - /home/ubuntu/docker-volumes/node1/zerotier-one:/var/lib/zerotier-one 
    command: bash -c "(rostopic list) && (rosrun topic_tools relay /turtle1/cmd_vel /cmd_vel) & (rosrun turtlesim turtle_teleop_key)"
    stdin_open: true

  echo:
    extends:
      file: "../ros-indigo-zt/docker-compose.yml"
      service: master
    container_name: echo
    hostname: echo
    volumes:
      - /home/ubuntu/docker-volumes/node2/zerotier-one:/var/lib/zerotier-one 
    command: bash -c "until rostopic list|grep -e '^/cmd_vel'; do echo waiting for /cmd_vel; done && rostopic echo /cmd_vel"

